import { Expense, Category, PaymentMode } from '../context/ExpenseContext';
import { formatAmount } from './format';

export const generateDashboardPDFHTML = (
  expenses: Expense[],
  categories: Category[],
  paymentModes: PaymentMode[],
  currency: string
) => {
  const tableRows = expenses.map(exp => {
    const cat = categories.find(c => c.id === exp.categoryId);
    const mode = paymentModes.find(m => m.id === exp.paymentModeId);
    return `
      <tr>
        <td>${new Date(exp.date).toLocaleDateString()}</td>
        <td>${exp.description}</td>
        <td>${cat ? cat.name : ''}</td>
        <td>${mode ? mode.name : ''}</td>
        <td style="text-align: right; color: #ff4444;">${formatAmount(exp.amount)}</td>
      </tr>
    `;
  }).join('');

  const total = expenses.reduce((sum, e) => sum + e.amount, 0);

  return `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
          h1 { text-align: center; color: #2c3e50; }
          .summary { font-size: 18px; margin-bottom: 20px; font-weight: bold; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background-color: #f8f9fa; color: #2c3e50; }
          tr:nth-child(even) { background-color: #f2f2f2; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #888; }
        </style>
      </head>
      <body>
        <h1>Expense Report</h1>
        <div class="summary">Total Expenses: ${currency}${formatAmount(total)} (${expenses.length} records)</div>
        <table>
          <thead>
            <tr>
              <th style="text-align: center;">Date</th>
              <th style="text-align: center;">Description</th>
              <th style="text-align: center;">Category</th>
              <th style="text-align: center;">Payment Mode</th>
              <th style="text-align: center;">Amount (${currency})</th>
            </tr>
          </thead>
          <tbody>
            ${tableRows.length > 0 ? tableRows : '<tr><td colspan="5" style="text-align: center;">No expenses found</td></tr>'}
          </tbody>
        </table>
        <div class="footer">Generated by Expense Manager</div>
      </body>
    </html>
  `;
};

const generateSVGChart = (
  data: { amount: number; color: string }[], 
  chartType: 'Pie' | 'Donut', 
  chartStyle: 'Classic' | '3D' | 'Spaced' | 'Semi-Circle'
) => {
  const total = data.reduce((sum, item) => sum + item.amount, 0);
  if (total === 0) {
    return `<div style="text-align: center; margin: 20px 0;"><svg width="200" height="200" viewBox="-1.1 -1.1 2.2 2.2"><circle cx="0" cy="0" r="1" fill="#eee" /></svg></div>`;
  }

  const isSemi = chartStyle === 'Semi-Circle';
  const isDonut = chartType === 'Donut';
  const isSpaced = chartStyle === 'Spaced';
  
  let svgContent = '';
  let cumulativePercent = 0;

  const angleMultiplier = isSemi ? 1 : 2;

  data.forEach((slice) => {
    if (slice.amount === 0) return;
    const percent = slice.amount / total;

    if (percent === 1) {
      if (isSemi) {
        // Draw a half circle
        svgContent += `<path d="M 1 0 A 1 1 0 0 1 -1 0 Z" fill="${slice.color}" />`;
      } else {
        svgContent += `<circle cx="0" cy="0" r="1" fill="${slice.color}" />`;
      }
      return;
    }

    const startX = Math.cos(angleMultiplier * Math.PI * cumulativePercent);
    const startY = Math.sin(angleMultiplier * Math.PI * cumulativePercent);
    cumulativePercent += percent;
    const endX = Math.cos(angleMultiplier * Math.PI * cumulativePercent);
    const endY = Math.sin(angleMultiplier * Math.PI * cumulativePercent);

    const largeArcFlag = isSemi ? 0 : (percent > 0.5 ? 1 : 0);

    const strokeAttr = isSpaced ? 'stroke="#ffffff" stroke-width="0.05"' : '';
    svgContent += `<path d="M 0 0 L ${startX} ${startY} A 1 1 0 ${largeArcFlag} 1 ${endX} ${endY} Z" fill="${slice.color}" ${strokeAttr} />`;
  });

  const maskDef = isDonut ? `
    <defs>
      <mask id="donut-mask">
        <rect x="-1.5" y="-1.5" width="3" height="3" fill="white" />
        <circle cx="0" cy="0" r="0.5" fill="black" />
      </mask>
    </defs>
  ` : '';

  const groupAttr = isDonut ? `mask="url(#donut-mask)"` : '';
  const transformAttr = isSemi ? `rotate(180)` : `rotate(-90)`;
  const filterAttr = chartStyle === '3D' ? `filter: drop-shadow(3px 3px 2px rgba(0,0,0,0.3));` : ``;

  return `
    <div style="text-align: center; margin: 20px 0;">
      <svg width="200" height="${isSemi ? 100 : 200}" viewBox="-1.1 -1.1 2.2 ${isSemi ? 1.1 : 2.2}" style="${filterAttr}">
        ${maskDef}
        <g transform="${transformAttr}" ${groupAttr}>
          ${svgContent}
        </g>
      </svg>
    </div>
  `;
};

export const generateAnalyticsPDFHTML = (
  filterName: string,
  totalSpent: number,
  categoryData: { name: string; amount: number; color: string; text: string }[],
  paymentModeData: { name: string; amount: number; color: string; text: string }[],
  currency: string,
  chartType: 'Pie' | 'Donut' = 'Pie',
  chartStyle: 'Classic' | '3D' | 'Spaced' | 'Semi-Circle' = 'Classic'
) => {
  const catRows = categoryData.map(cat => `
    <tr>
      <td>
        <span style="display:inline-block; width:12px; height:12px; border-radius:50%; background-color:${cat.color}; margin-right:8px;"></span>
        ${cat.name}
      </td>
      <td style="text-align: right;">${cat.text}</td>
      <td style="text-align: right;">${currency}${formatAmount(cat.amount)}</td>
    </tr>
  `).join('');

  const modeRows = paymentModeData.map(mode => `
    <tr>
      <td>
        <span style="display:inline-block; width:12px; height:12px; border-radius:50%; background-color:${mode.color}; margin-right:8px;"></span>
        ${mode.name}
      </td>
      <td style="text-align: right;">${mode.text}</td>
      <td style="text-align: right;">${currency}${formatAmount(mode.amount)}</td>
    </tr>
  `).join('');

  return `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
          h1 { text-align: center; color: #2c3e50; margin-bottom: 5px; }
          .subtitle { text-align: center; color: #7f8c8d; font-size: 16px; margin-bottom: 30px; }
          .card { background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
          .card h2 { margin-top: 0; color: #2c3e50; font-size: 18px; border-bottom: 1px solid #eee; padding-bottom: 10px; }
          .total-spent { font-size: 32px; font-weight: bold; color: #2c3e50; text-align: center; margin: 10px 0; }
          table { width: 100%; border-collapse: collapse; }
          th, td { padding: 12px 8px; border-bottom: 1px solid #eee; text-align: left; }
          th { color: #888; font-size: 12px; text-transform: uppercase; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #888; }
        </style>
      </head>
      <body>
        <h1>Analytics Report</h1>
        <div class="subtitle">Period: ${filterName}</div>
        
        <div class="card">
          <h2>Total Spent</h2>
          <div class="total-spent">${currency}${formatAmount(totalSpent)}</div>
        </div>

        <div class="card">
          <h2>Category Breakdown</h2>
          ${generateSVGChart(categoryData, chartType, chartStyle)}
          <table>
            <thead>
              <tr>
                <th>Category</th>
                <th style="text-align: right;">Percentage (%)</th>
                <th style="text-align: right;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${catRows.length > 0 ? catRows : '<tr><td colspan="3" style="text-align: center;">No data</td></tr>'}
            </tbody>
          </table>
        </div>

        <div class="card">
          <h2>Payment Mode</h2>
          ${generateSVGChart(paymentModeData, chartType, chartStyle)}
          <table>
            <thead>
              <tr>
                <th>Payment Mode</th>
                <th style="text-align: right;">Percentage (%)</th>
                <th style="text-align: right;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${modeRows.length > 0 ? modeRows : '<tr><td colspan="3" style="text-align: center;">No data</td></tr>'}
            </tbody>
          </table>
        </div>

        <div class="footer">Generated by Expense Manager</div>
      </body>
    </html>
  `;
};
